# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  branches:
    "dev":
      - step:
          name: Test
          artifacts:
            - node_modules/*
          caches:
            - node
          script: # Modify the commands below to build your repository.
            - npm install
            - npm test
      - step:
          name: Deploy to staging
          deployment: staging
          script:
          #Install ssh
           - apt-get update -y
           - apt-get install -y ssh
           - cat ./deploy.sh | ssh ubuntu@ec2-3-124-175-241.eu-central-1.compute.amazonaws.com
           - echo "Deploy step finished"
